development:
  secret_key_base: ae3e5f1fc050c52626a51456a73801eec65142f5e51584c227af14c8a2b7e82d5e8e72bc2f5b0e017b3ab8ea538d9e032a1affa1e56d8aa6b59557107095ab04

test:
  secret_key_base: 58649324629118be93eb5014197a0c716feba279f9a7acb2cfb88bb2244e79fb1e93fbfff2bb981d09f562ab16afaa1632ee88bfe41ef65946073455e90bb0be

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
